name: Repo Dispatch to EDJRuntime and EDJOS

on:
  workflow_call:
    inputs:
      repo:
        required: true
        type: string
      longVersion:
        required: true
        type: string
      release:
        required: true
        type: string
    secrets:
      EDJX_GH_TOKEN:
        required: true

jobs:
  dispatch:
    name: Update edjos and edjruntime Manifest
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/heads/development') || startsWith(github.ref, 'refs/tags/')
    strategy:
      matrix:
        repository: [edjx/edjruntime, edjx/edjos]

    steps:
      - name: Dispatch Version
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ inputs.EDJX_GH_TOKEN }}
          repository: ${{ matrix.repository }}
          event-type: "${{ inputs.repo }}"
          client-payload: '{
            "version": "${{ inputs.longVersion }}",
            "variable": "${{ inputs.repo }}",
            "release": "${{ inputs.release }}"
            }'
