name: Docker Builder

on:
  workflow_call:
    inputs:
      imageName:
        required: true
        type: string
      imageDescription:
        required: false
        type: string

jobs:
  docker:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: "0"
          submodules: recursive
          token: ${{ secrets.EDJNET_GITHUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Metadata for pushes to development
        id: metadata
        uses: docker/metadata-action@v4
        with:
          labels: |
            org.opencontainers.image.description=${{ inputs.imageDescription }}
            org.opencontainers.image.licenses=EDJX Proprietary
          images: |
            ghcr.io/edjx/${{ inputs.imageName }}
          tags: |
            type=raw,value={{ date 'YY' }}.{{ date 'MM'}}.0-{{sha}},event=push
            type=match,pattern=v(\d+.\d+.\d+),group=1
            type=raw,latest
            type=raw, value=${{ github.run_number }}

      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
